services:
  backend:
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    working_dir: /source
    volumes:
      - ./app:/source/app
    ports:
      - 8000:8000
    restart: always
    networks:
      - default
    env_file:
      - .env

    build:
      context: .
    platform: linux/amd64 # Patch for M1 Mac
